version: '3'
services:
  app:
    container_name: ${NAME}
    image: python
    #restart: always
    volumes:
      - type: bind
        source: ~/scrapy
        target: /app
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
    - "TEST=${TEST}"